_wandb:
    value:
        cli_version: 0.21.4
        e:
            mj8vrmlhvneal4g08dy9ksnhklr8wm2z:
                apple:
                    ecpuCores: 4
                    gpuCores: 10
                    memoryGb: 8
                    name: Apple M2
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "5368709120"
                args:
                    - →
                    - port
                    - "8000"
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "92897026048"
                email: gunalsoftware@gmail.com
                executable: /opt/anaconda3/bin/python
                host: Gunals-MacBook-Pro.local
                memory:
                    total: "8589934592"
                os: macOS-15.6.1-arm64-arm-64bit-Mach-O
                program: -m src.task2_llm_storage
                python: CPython 3.13.5
                root: /Users/gunal/Developer/Data-Science-Projects/cls-project/ai-data-engineering-assignment
                startedAt: "2025-09-14T19:14:38.016819Z"
                writerId: mj8vrmlhvneal4g08dy9ksnhklr8wm2z
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 75
                - 92
                - 95
                - 97
                - 105
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 75
                - 92
                - 95
                - 97
                - 105
            "3":
                - 13
                - 15
            "4": 3.13.5
            "5": 0.21.4
            "6": 4.56.1
            "12": 0.21.4
            "13": darwin-arm64
