_wandb:
    value:
        cli_version: 0.21.4
        e:
            h8mtkq7mdvny0pgtxal5x49id0bnryay:
                apple:
                    ecpuCores: 4
                    gpuCores: 10
                    memoryGb: 8
                    name: Apple M2
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "4294967296"
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "91835469824"
                email: gunalsoftware@gmail.com
                executable: /opt/anaconda3/bin/python
                host: Gunals-MacBook-Pro.local
                memory:
                    total: "8589934592"
                os: macOS-15.6.1-arm64-arm-64bit-Mach-O
                program: -m src.task1_ocr_nlp
                python: CPython 3.13.5
                root: /Users/gunal/Developer/Data-Science-Projects/cls-project/project
                startedAt: "2025-09-14T18:41:34.367493Z"
                writerId: h8mtkq7mdvny0pgtxal5x49id0bnryay
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 1
                - 5
                - 33
                - 53
                - 105
            "2":
                - 1
                - 5
                - 33
                - 53
                - 105
            "3":
                - 13
            "4": 3.13.5
            "5": 0.21.4
            "12": 0.21.4
            "13": darwin-arm64
